import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#004532',
        'primary-container': '#065f46',
        'on-primary': '#ffffff',
        'on-primary-container': '#8bd6b7',
        'on-primary-fixed': '#002116',
        'primary-fixed': '#a6f2d1',
        'primary-fixed-dim': '#8bd6b6',
        'on-primary-fixed-variant': '#00513b',
        secondary: '#006c49',
        'secondary-container': '#6cf8bb',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#00714d',
        'secondary-fixed': '#6ffbbe',
        'secondary-fixed-dim': '#4edea3',
        'on-secondary-fixed': '#002113',
        'on-secondary-fixed-variant': '#005236',
        tertiary: '#333f39',
        'tertiary-container': '#4a564f',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#becac2',
        'tertiary-fixed': '#d9e6dd',
        'tertiary-fixed-dim': '#bdcac1',
        'on-tertiary-fixed': '#131e19',
        'on-tertiary-fixed-variant': '#3e4943',
        background: '#f9f9ff',
        'on-background': '#151c27',
        surface: '#f9f9ff',
        'on-surface': '#151c27',
        'surface-variant': '#dce2f3',
        'on-surface-variant': '#3f4944',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f0f3ff',
        'surface-container': '#e7eefe',
        'surface-container-high': '#e2e8f8',
        'surface-container-highest': '#dce2f3',
        'surface-bright': '#f9f9ff',
        'surface-dim': '#d3daea',
        'surface-tint': '#1b6b51',
        'inverse-surface': '#2a313d',
        'inverse-on-surface': '#ebf1ff',
        'inverse-primary': '#8bd6b6',
        outline: '#6f7973',
        'outline-variant': '#bec9c2',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        gutter: '1.5rem',
        'container-max': '1280px',
        md: '1.5rem',
        sm: '1rem',
        base: '4px',
        xs: '0.5rem',
        xl: '3rem',
        lg: '2rem',
      },
      fontFamily: {
        inter: ['Inter', 'sans-serif'],
        'body-md': ['Inter'],
        'body-sm': ['Inter'],
        h1: ['Inter'],
        h2: ['Inter'],
        h3: ['Inter'],
        'body-lg': ['Inter'],
        'label-caps': ['Inter'],
        button: ['Inter'],
      },
      fontSize: {
        h1: ['40px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        h2: ['30px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        h3: ['24px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
        button: ['14px', { lineHeight: '1', letterSpacing: '0.01em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}

export default config
