import {
  createContext,
  useContext,
  useEffect,
  useMemo,
  useState,
  type ReactNode,
} from 'react'

export type Language = 'id' | 'en' | 'zh'

type Params = Record<string, string | number>

const LANGUAGE_KEY = 'mftc_language'

const messages: Record<Language, Record<string, string>> = {
  id: {
    'common.loading': 'Memuat...',
    'common.login': 'Login',
    'common.register': 'Daftar',
    'common.dashboard': 'Dashboard',
    'common.language': 'Bahasa',
    'auth.brand.login': 'MFT Certify',
    'auth.brand.register': 'HalalCertify',
    'auth.portal': 'MFTC Portal',
    'auth.login.hero.title': 'Membangun Kepercayaan Melalui Sertifikasi Halal Global.',
    'auth.login.hero.description': 'Akses portal manajemen untuk memantau standar, aplikasi, dan kepatuhan pariwisata ramah Muslim Anda.',
    'auth.login.globalReach': 'Global Reach',
    'auth.login.certifiedRegions': 'Certified Regions',
    'auth.login.reliability': 'Reliability',
    'auth.login.complianceRate': 'Compliance Rate',
    'auth.login.title': 'Masuk ke MFT Portal',
    'auth.login.subtitle': 'Kelola sertifikasi Muslim Friendly Tourism Anda dengan aman.',
    'auth.login.email': 'Alamat Email',
    'auth.login.emailPlaceholder': 'nama@perusahaan.com',
    'auth.login.password': 'Kata Sandi',
    'auth.login.forgot': 'Lupa sandi?',
    'auth.login.remember': 'Tetap masuk selama 30 hari',
    'auth.login.submit': 'Masuk Sekarang',
    'auth.login.processing': 'Memproses…',
    'auth.login.or': 'Atau masuk dengan',
    'auth.login.google': 'Masuk dengan Google',
    'auth.login.noAccount': 'Belum punya akun?',
    'auth.login.registerLink': 'Daftar Sertifikasi',
    'auth.login.failed': 'Login gagal. Silakan coba lagi.',
    'auth.register.badge': 'Trusted certification onboarding',
    'auth.register.hero.title': 'Elevating global standards for Muslim-friendly tourism.',
    'auth.register.hero.description': 'Join tourism providers completing the Muslim Friendly Tourism Certification process with a guided, secure, and transparent digital workflow.',
    'auth.register.stat.partners': 'Certified partners',
    'auth.register.stat.countries': 'Countries',
    'auth.register.stat.integrity': 'Integrity rate',
    'auth.register.role': 'Pelaku Usaha',
    'auth.register.title': 'Daftar Akun MFTC',
    'auth.register.subtitle': 'Lengkapi data di bawah ini untuk memulai proses sertifikasi Anda sebagai Pelaku Usaha (PU).',
    'auth.register.fullName': 'Nama Lengkap',
    'auth.register.fullNamePlaceholder': 'Contoh: Ahmad Abdullah',
    'auth.register.email': 'Email Bisnis',
    'auth.register.phone': 'Nomor Telepon / WhatsApp',
    'auth.register.password': 'Kata Sandi',
    'auth.register.passwordPlaceholder': 'Minimal 8 karakter',
    'auth.register.passwordHelp': 'Minimal 8 karakter dengan kombinasi huruf dan angka.',
    'auth.register.confirmPassword': 'Konfirmasi Kata Sandi',
    'auth.register.confirmPasswordPlaceholder': 'Ulangi kata sandi',
    'auth.register.termsPrefix': 'Saya menyetujui',
    'auth.register.terms': 'Syarat & Ketentuan',
    'auth.register.privacyPrefix': 'serta',
    'auth.register.privacy': 'Kebijakan Privasi',
    'auth.register.termsSuffix': 'MFTC.',
    'auth.register.submit': 'Daftar Sekarang',
    'auth.register.submitting': 'Mendaftar...',
    'auth.register.haveAccount': 'Sudah memiliki akun?',
    'auth.register.loginLink': 'Login di sini',
    'auth.register.failed': 'Registrasi gagal. Silakan coba lagi.',
    'auth.validation.email': 'Email tidak valid.',
    'auth.validation.passwordMin': 'Kata sandi minimal 8 karakter.',
    'auth.validation.fullNameRequired': 'Nama lengkap wajib diisi',
    'auth.validation.emailInvalid': 'Format email tidak valid',
    'auth.validation.passwordRegisterMin': 'Minimal 8 karakter',
    'auth.validation.passwordCombination': 'Harus kombinasi huruf dan angka',
    'auth.validation.terms': 'Anda harus menyetujui syarat & ketentuan',
    'auth.validation.passwordConfirmation': 'Konfirmasi kata sandi tidak cocok',
    'auth.password.hide': 'Sembunyikan kata sandi',
    'auth.password.show': 'Tampilkan kata sandi',
    'auth.password.hideConfirm': 'Sembunyikan konfirmasi kata sandi',
    'auth.password.showConfirm': 'Tampilkan konfirmasi kata sandi',
    'public.nav.home': 'Beranda',
    'public.nav.standards': 'Standar',
    'public.nav.pricing': 'Harga',
    'public.nav.about': 'Tentang',
    'public.footer.links': 'Tautan',
    'public.footer.about': 'Tentang MFTC',
    'public.footer.standards': 'Standar',
    'public.footer.verify': 'Verifikasi Sertifikat',
    'public.footer.follow': 'Ikuti Kami',
    'public.footer.description': 'Memimpin transformasi pariwisata global menuju ekosistem ramah Muslim yang inklusif, menghormati, dan tersertifikasi.',
    'public.footer.privacy': 'Kebijakan Privasi',
    'public.footer.terms': 'Syarat Layanan',
    'public.footer.support': 'Kontak Dukungan',
    Page: 'Halaman',
    of: 'dari',
    Total: 'Total',
    'pu.title': 'Dashboard PU',
    'pu.sidebar.dashboard': 'Dashboard',
    'pu.sidebar.profile': 'Profil Usaha',
    'pu.sidebar.applications': 'Pengajuan',
    'pu.sidebar.certificates': 'Sertifikat',
    'pu.sidebar.help': 'Pusat Bantuan',
    'pu.logout': 'Logout',
    'pu.logout.loading': 'Logging out…',
    'notifications.title': 'Notifikasi',
    'notifications.subtitle': 'Aktivitas terbaru dari tim LPH',
    'notifications.empty': 'Belum ada aktivitas terbaru.',
    'landing.badge': 'Standar Global untuk Keunggulan',
    'landing.hero.title': 'Meningkatkan Pariwisata Ramah Muslim ke Standar Global',
    'landing.hero.description': 'Muslim Friendly Tourism Certification (MFTC) menyediakan kerangka kerja komprehensif untuk memastikan integritas, kualitas, dan keramahan bagi pasar wisata Muslim global.',
    'landing.hero.start': 'Mulai Sertifikasi',
    'landing.hero.standards': 'Lihat Standar',
    'landing.iso.title': 'Patuh ISO',
    'landing.iso.subtitle': 'Standar Internasional',
    'landing.levels.title': 'Level Sertifikasi',
    'landing.levels.description': 'Standar bertingkat yang dirancang untuk mengakui dan meningkatkan kualitas layanan ramah Muslim secara global.',
    'landing.level.one.title': 'Satu Bintang',
    'landing.level.one.label': 'LEVEL DASAR',
    'landing.level.one.description': 'Sertifikasi awal yang berfokus pada fasilitas ibadah esensial dan aksesibilitas makanan halal.',
    'landing.level.two.title': 'Dua Bintang',
    'landing.level.two.label': 'KEUNGGULAN MENENGAH',
    'landing.level.two.description': 'Sertifikasi lanjutan termasuk pelatihan staf hospitality khusus dan fitur privasi fasilitas yang ditingkatkan.',
    'landing.level.three.title': 'Tiga Bintang',
    'landing.level.three.label': 'PENGAKUAN PREMIUM',
    'landing.level.three.description': 'Standar emas untuk layanan premium ramah Muslim, integrasi ekosistem penuh, dan layanan kelas dunia.',
    'landing.scope.title': 'Ruang Lingkup Sertifikasi',
    'landing.scope.description': 'Kami menyediakan layanan audit dan sertifikasi khusus di seluruh rantai nilai pariwisata.',
    'landing.scope.viewAll': 'Lihat Semua Ruang Lingkup',
    'landing.scope.hotel': 'Hotel',
    'landing.scope.restaurant': 'Restoran',
    'landing.scope.travelAgent': 'Agen Perjalanan',
    'landing.scope.attractions': 'Atraksi',
    'landing.scope.shopping': 'Belanja',
    'landing.scope.transport': 'Transportasi',
    'landing.scope.medical': 'Medis',
    'landing.scope.events': 'Acara',
    'landing.scope.holySites': 'Situs Suci',
    'landing.scope.consultancy': 'Konsultansi',
    'landing.stats.partners': 'Mitra Tersertifikasi',
    'landing.stats.countries': 'Negara',
    'landing.stats.rooms': 'Kamar Diaudit',
    'landing.stats.integrity': 'Tingkat Integritas',
    'standards.badge': 'Panduan Resmi 2025',
    'standards.hero.title': 'Standar Pariwisata Ramah Muslim (MFTC)',
    'standards.hero.description': 'Acuan komprehensif untuk meningkatkan standar pelayanan pariwisata ramah Muslim di Indonesia, memastikan kenyamanan, kepercayaan, dan kepatuhan global.',
    'standards.hero.criteria': 'Pelajari Kriteria',
    'standards.hero.download': 'Unduh Dokumen',
    'standards.criteria.title': 'Kriteria Utama',
    'standards.criteria.prayer.title': 'Fasilitas Ibadah',
    'standards.criteria.prayer.description': 'Ketersediaan ruang sholat yang bersih, arah kiblat yang presisi, serta fasilitas wudhu yang memadai dan terpisah.',
    'standards.criteria.food.title': 'Makanan Halal',
    'standards.criteria.food.description': 'Jaminan proses penyediaan makanan dan minuman yang bersertifikat Halal, mulai dari bahan baku hingga penyajian.',
    'standards.criteria.service.title': 'Pelayanan Umum',
    'standards.criteria.service.description': 'Staf yang terlatih dalam etika pelayanan ramah Muslim dan pemahaman mendalam tentang kebutuhan tamu.',
    'standards.criteria.sanitation.title': 'Higienitas & Sanitasi',
    'standards.criteria.sanitation.description': 'Standar kebersihan yang ketat pada seluruh area publik dan toilet yang mendukung konsep Thaharah.',
    'standards.matrix.title': 'Matriks Level Bintang',
    'standards.matrix.description': 'Perbandingan persyaratan standar berdasarkan tingkatan sertifikasi',
    'standards.matrix.criteria': 'Kriteria Penilaian',
    'standards.matrix.one': 'Satu Bintang',
    'standards.matrix.two': 'Dua Bintang',
    'standards.matrix.three': 'Tiga Bintang',
    'standards.matrix.prayer': 'Penyediaan Musholla',
    'standards.matrix.prayer.one': 'Wajib (Tersedia)',
    'standards.matrix.prayer.two': 'Wajib (Luas & Nyaman)',
    'standards.matrix.prayer.three': 'Eksklusif (Fasilitas Premium)',
    'standards.matrix.menu': 'Menu Halal',
    'standards.matrix.menu.one': 'Minimal 50% Menu',
    'standards.matrix.menu.two': 'Minimal 75% Menu',
    'standards.matrix.menu.three': '100% Tersertifikasi Halal',
    'standards.matrix.toilet': 'Toilet ramah Muslim',
    'standards.matrix.toilet.one': 'Sesuai Standar Umum',
    'standards.matrix.toilet.two': 'Peralatan Istinja Lengkap',
    'standards.matrix.toilet.three': 'Sistem Sanitasi Canggih',
    'standards.matrix.hygiene': 'Memiliki sertifikat laik hygiene',
    'standards.matrix.hygiene.one': 'Opsional',
    'standards.matrix.hygiene.two': 'Direkomendasikan',
    'standards.matrix.hygiene.three': 'Wajib',
    'standards.documents.title': 'Dokumen Acuan',
    'standards.documents.description': 'Unduh dokumen standar operasional dan prosedur teknis untuk persiapan sertifikasi MFTC.',
    'standards.documents.viewAll': 'Lihat Semua Arsip',
    'standards.documents.standard.title': 'Standar MFTC 2025',
    'standards.documents.standard.subtitle': 'Panduan Utama Kriteria Sertifikasi Baru',
    'standards.documents.procedure.title': 'PO/HALAL-PPS/04',
    'standards.documents.procedure.subtitle': 'Prosedur Operasional Penjaminan Halal',
    'standards.documents.self.title': 'Formulir Self-Assessment',
    'standards.documents.self.subtitle': 'Dokumen Persiapan Audit Internal',
    'standards.documents.hygiene.title': 'Panduan Higienitas 2.0',
    'standards.documents.hygiene.subtitle': 'Standar Sanitasi Thaharah untuk Hotel',
    'pricing.badge': 'Transparan & Terpercaya',
    'pricing.hero.title': 'Investasi untuk Keunggulan',
    'pricing.hero.highlight': 'Muslim Friendly Tourism',
    'pricing.hero.description': 'Struktur biaya yang dirancang secara profesional, mencerminkan standar sertifikasi internasional yang diakui secara global.',
    'pricing.card.badge': 'Paket Sertifikasi',
    'pricing.card.title': 'Sertifikasi MFTC',
    'pricing.card.description': 'Muslim Friendly Tourism Certification resmi oleh Sucofindo International Certification Services.',
    'pricing.card.starting': 'Mulai dari',
    'pricing.card.currency': 'Rp',
    'pricing.card.price': '6,5 Jt',
    'pricing.card.tax': 'Belum termasuk PPN 11%',
    'pricing.card.start': 'Mulai Sertifikasi',
    'pricing.card.learn': 'Pelajari Lebih Lanjut',
    'pricing.included.title': 'Yang Tercakup dalam Biaya',
    'pricing.included.description': 'Setiap pengajuan mencakup layanan audit komprehensif dua tahap sesuai Standar Pariwisata Ramah Muslim.',
    'pricing.feature.audit.title': 'Audit Dua Tahap',
    'pricing.feature.audit.desc': 'Audit Tahap I (dokumen) dan Tahap II (kunjungan lapangan) oleh auditor bersertifikat.',
    'pricing.feature.certificate.title': 'Sertifikat Resmi MFTC',
    'pricing.feature.certificate.desc': 'Sertifikat berlaku 5 tahun, diterbitkan oleh Sucofindo International Certification Services.',
    'pricing.feature.assist.title': 'Pendampingan Proses',
    'pricing.feature.assist.desc': 'Tim Sales dan Auditor kami mendampingi seluruh proses dari pengajuan hingga penerbitan sertifikat.',
    'pricing.feature.multi.title': 'Fleksibel Multi-Lokasi',
    'pricing.feature.multi.desc': 'Jumlah mandays disesuaikan dengan jumlah lokasi dan ruang lingkup yang diajukan.',
    'pricing.feature.international.title': 'Layanan Internasional',
    'pricing.feature.international.desc': 'Travel allowance auditor dapat disesuaikan untuk klien di luar negeri.',
    'pricing.notes.title': 'Informasi Biaya',
    'pricing.notes.vat': 'Biaya yang tertera belum termasuk PPN sebesar 11%.',
    'pricing.notes.mandays': 'Jumlah mandays ditetapkan berdasarkan jumlah lokasi dan ruang lingkup yang diajukan.',
    'pricing.notes.initial': 'Biaya ini berlaku untuk sertifikasi awal dan belum mencakup biaya surveilans tahunan.',
    'pricing.notes.travel': 'Travel allowance auditor dapat disesuaikan untuk penugasan di luar negeri.',
    'pricing.badge.international.title': 'Diakui Internasional',
    'pricing.badge.international.desc': 'Standar MFTC diakui oleh lembaga pariwisata internasional.',
    'pricing.badge.consult.title': 'Konsultasi Gratis',
    'pricing.badge.consult.desc': 'Tim kami siap memandu Anda sebelum memulai proses sertifikasi.',
    'pricing.badge.transparent.title': 'Harga Transparan',
    'pricing.badge.transparent.desc': 'Tidak ada biaya tersembunyi. Semua komponen biaya disampaikan di awal.',
    'pricing.cta.question': 'Membutuhkan penawaran khusus untuk skala enterprise?',
    'pricing.cta.link': 'Hubungi tim kami →',
    'about.hero.badge': 'Pelopor Standarisasi Global',
    'about.hero.title': 'Tentang MFTC: Mengangkat Standar Pariwisata Muslim Indonesia ke Tingkat Global',
    'about.hero.standards': 'Pelajari Standar Kami',
    'about.hero.contact': 'Hubungi Tim Ahli',
    'about.stats.partners': 'Mitra Bersertifikat',
    'about.stats.provinces': 'Provinsi Terjangkau',
    'about.stats.compliance': 'Kepatuhan Syariah',
    'about.mission.title': 'Misi Kami untuk Indonesia',
    'about.mission.description': 'Muslim-Friendly Tourism Certification (MFTC) lahir dari visi besar untuk menjadikan Indonesia sebagai pusat pariwisata halal dunia. Kami menjembatani kesenjangan antara potensi wisata lokal dengan ekspektasi wisatawan Muslim global melalui standarisasi yang kredibel dan terukur.',
    'about.accreditation.title': 'Akreditasi Terpercaya',
    'about.accreditation.description': 'Setiap sertifikat yang kami terbitkan merupakan hasil audit ketat yang mengacu pada fatwa DSN-MUI dan standar global pariwisata halal.',
    'about.values.badge': 'Pilar Utama',
    'about.values.title': 'Nilai-Nilai Utama Kami',
    'about.values.integrity.title': 'Integritas',
    'about.values.integrity.description': 'Kami memegang teguh kejujuran dalam setiap proses verifikasi, memastikan transparansi penuh bagi seluruh pemangku kepentingan dalam ekosistem pariwisata.',
    'about.values.professional.title': 'Profesionalisme',
    'about.values.professional.description': 'Didukung oleh auditor bersertifikat dan tenaga ahli industri, kami memberikan layanan sertifikasi dengan standar operasional terbaik di kelasnya.',
    'about.values.sharia.title': 'Kepatuhan Syariah',
    'about.values.sharia.description': 'Setiap indikator penilaian kami selaras dengan nilai-nilai Islami, menjamin kenyamanan ibadah dan konsumsi halal bagi para wisatawan.',
    'about.partner.badge': 'Mitra Resmi',
    'about.partner.title': 'Kolaborasi Strategis dengan PT Sucofindo',
    'about.partner.description': 'MFTC menjalin kemitraan eksklusif dengan PT Sucofindo sebagai lembaga sertifikasi resmi. Sinergi ini menggabungkan keahlian audit teknis Sucofindo selama puluhan tahun dengan spesialisasi MFTC dalam standar ramah Muslim.',
    'about.partner.audit': 'Audit Independen & Objektif',
    'about.partner.recognition': 'Pengakuan Nasional & Internasional',
    'about.partner.digital': 'Proses Terintegrasi Sistem Digital',
    'about.partner.body': 'Lembaga Sertifikasi Resmi',
  },
  en: {
    'common.loading': 'Loading...',
    'common.login': 'Login',
    'common.register': 'Register',
    'common.dashboard': 'Dashboard',
    'common.language': 'Language',
    'auth.brand.login': 'MFT Certify',
    'auth.brand.register': 'HalalCertify',
    'auth.portal': 'MFTC Portal',
    'auth.login.hero.title': 'Building Trust Through Global Halal Certification.',
    'auth.login.hero.description': 'Access the management portal to monitor your Muslim-friendly tourism standards, applications, and compliance.',
    'auth.login.globalReach': 'Global Reach',
    'auth.login.certifiedRegions': 'Certified Regions',
    'auth.login.reliability': 'Reliability',
    'auth.login.complianceRate': 'Compliance Rate',
    'auth.login.title': 'Sign in to MFT Portal',
    'auth.login.subtitle': 'Manage your Muslim Friendly Tourism certification securely.',
    'auth.login.email': 'Email Address',
    'auth.login.emailPlaceholder': 'name@company.com',
    'auth.login.password': 'Password',
    'auth.login.forgot': 'Forgot password?',
    'auth.login.remember': 'Keep me signed in for 30 days',
    'auth.login.submit': 'Sign In Now',
    'auth.login.processing': 'Processing…',
    'auth.login.or': 'Or sign in with',
    'auth.login.google': 'Sign in with Google',
    'auth.login.noAccount': 'Don’t have an account?',
    'auth.login.registerLink': 'Register Certification',
    'auth.login.failed': 'Login failed. Please try again.',
    'auth.register.badge': 'Trusted certification onboarding',
    'auth.register.hero.title': 'Elevating global standards for Muslim-friendly tourism.',
    'auth.register.hero.description': 'Join tourism providers completing the Muslim Friendly Tourism Certification process with a guided, secure, and transparent digital workflow.',
    'auth.register.stat.partners': 'Certified partners',
    'auth.register.stat.countries': 'Countries',
    'auth.register.stat.integrity': 'Integrity rate',
    'auth.register.role': 'Business Actor',
    'auth.register.title': 'Create MFTC Account',
    'auth.register.subtitle': 'Complete the data below to start your certification process as a business actor (PU).',
    'auth.register.fullName': 'Full Name',
    'auth.register.fullNamePlaceholder': 'Example: Ahmad Abdullah',
    'auth.register.email': 'Business Email',
    'auth.register.phone': 'Phone / WhatsApp Number',
    'auth.register.password': 'Password',
    'auth.register.passwordPlaceholder': 'Minimum 8 characters',
    'auth.register.passwordHelp': 'Minimum 8 characters with a combination of letters and numbers.',
    'auth.register.confirmPassword': 'Confirm Password',
    'auth.register.confirmPasswordPlaceholder': 'Repeat password',
    'auth.register.termsPrefix': 'I agree to the',
    'auth.register.terms': 'Terms & Conditions',
    'auth.register.privacyPrefix': 'and',
    'auth.register.privacy': 'Privacy Policy',
    'auth.register.termsSuffix': 'of MFTC.',
    'auth.register.submit': 'Register Now',
    'auth.register.submitting': 'Registering...',
    'auth.register.haveAccount': 'Already have an account?',
    'auth.register.loginLink': 'Login here',
    'auth.register.failed': 'Registration failed. Please try again.',
    'auth.validation.email': 'Invalid email.',
    'auth.validation.passwordMin': 'Password must be at least 8 characters.',
    'auth.validation.fullNameRequired': 'Full name is required',
    'auth.validation.emailInvalid': 'Invalid email format',
    'auth.validation.passwordRegisterMin': 'Minimum 8 characters',
    'auth.validation.passwordCombination': 'Must contain letters and numbers',
    'auth.validation.terms': 'You must agree to the terms & conditions',
    'auth.validation.passwordConfirmation': 'Password confirmation does not match',
    'auth.password.hide': 'Hide password',
    'auth.password.show': 'Show password',
    'auth.password.hideConfirm': 'Hide password confirmation',
    'auth.password.showConfirm': 'Show password confirmation',
    'public.nav.home': 'Home',
    'public.nav.standards': 'Standards',
    'public.nav.pricing': 'Pricing',
    'public.nav.about': 'About',
    'public.footer.links': 'Links',
    'public.footer.about': 'About MFTC',
    'public.footer.standards': 'Standards',
    'public.footer.verify': 'Verify Certificate',
    'public.footer.follow': 'Follow Us',
    'public.footer.description': 'Leading the transformation of global tourism towards an inclusive, respectful, and certified Muslim-friendly ecosystem.',
    'public.footer.privacy': 'Privacy Policy',
    'public.footer.terms': 'Terms of Service',
    'public.footer.support': 'Contact Support',
    Page: 'Page',
    of: 'of',
    Total: 'Total',
    'pu.title': 'PU Dashboard',
    'pu.sidebar.dashboard': 'Dashboard',
    'pu.sidebar.profile': 'Business Profile',
    'pu.sidebar.applications': 'Applications',
    'pu.sidebar.certificates': 'Certificates',
    'pu.sidebar.help': 'Help Center',
    'pu.logout': 'Logout',
    'pu.logout.loading': 'Logging out…',
    'notifications.title': 'Notifications',
    'notifications.subtitle': 'Latest activities from LPH team',
    'notifications.empty': 'No recent activities.',
    'landing.badge': 'Global Standard for Excellence',
    'landing.hero.title': 'Elevating Muslim Friendly Tourism to Global Standards',
    'landing.hero.description': 'The Muslim Friendly Tourism Certification (MFTC) provides a comprehensive framework to ensure integrity, quality, and hospitality for the global Muslim travel market.',
    'landing.hero.start': 'Start Certification',
    'landing.hero.standards': 'View Standards',
    'landing.iso.title': 'ISO Compliant',
    'landing.iso.subtitle': 'International Standards',
    'landing.levels.title': 'Certification Levels',
    'landing.levels.description': 'Scalable standards designed to recognize and improve the quality of Muslim-friendly services globally.',
    'landing.level.one.title': 'One Star',
    'landing.level.one.label': 'FOUNDATIONAL LEVEL',
    'landing.level.one.description': 'Entry-level certification focused on essential prayer facilities and halal food accessibility requirements.',
    'landing.level.two.title': 'Two Star',
    'landing.level.two.label': 'INTERMEDIATE EXCELLENCE',
    'landing.level.two.description': 'Advanced certification including specialized hospitality staff training and enhanced facility privacy features.',
    'landing.level.three.title': 'Three Star',
    'landing.level.three.label': 'PREMIUM RECOGNITION',
    'landing.level.three.description': 'The gold standard for premium Muslim-friendly luxury, full eco-system integration, and world-class service.',
    'landing.scope.title': 'Certification Scope',
    'landing.scope.description': 'We provide specialized auditing and certification services across the entire tourism value chain.',
    'landing.scope.viewAll': 'View All Scopes',
    'landing.scope.hotel': 'Hotel',
    'landing.scope.restaurant': 'Restaurant',
    'landing.scope.travelAgent': 'Travel Agent',
    'landing.scope.attractions': 'Attractions',
    'landing.scope.shopping': 'Shopping',
    'landing.scope.transport': 'Transport',
    'landing.scope.medical': 'Medical',
    'landing.scope.events': 'Events',
    'landing.scope.holySites': 'Holy Sites',
    'landing.scope.consultancy': 'Consultancy',
    'landing.stats.partners': 'Certified Partners',
    'landing.stats.countries': 'Countries',
    'landing.stats.rooms': 'Audited Rooms',
    'landing.stats.integrity': 'Integrity Rate',
    'standards.badge': 'Official 2025 Guide',
    'standards.hero.title': 'Muslim Friendly Tourism Standards (MFTC)',
    'standards.hero.description': 'A comprehensive reference to improve Muslim-friendly tourism service standards in Indonesia while ensuring comfort, trust, and global compliance.',
    'standards.hero.criteria': 'Explore Criteria',
    'standards.hero.download': 'Download Documents',
    'standards.criteria.title': 'Main Criteria',
    'standards.criteria.prayer.title': 'Prayer Facilities',
    'standards.criteria.prayer.description': 'Availability of clean prayer rooms, accurate qibla direction, and adequate separated ablution facilities.',
    'standards.criteria.food.title': 'Halal Food',
    'standards.criteria.food.description': 'Assurance of certified halal food and beverage processes, from raw materials to serving.',
    'standards.criteria.service.title': 'General Service',
    'standards.criteria.service.description': 'Staff trained in Muslim-friendly service ethics and deep understanding of guest needs.',
    'standards.criteria.sanitation.title': 'Hygiene & Sanitation',
    'standards.criteria.sanitation.description': 'Strict cleanliness standards across public areas and toilets supporting the concept of thaharah.',
    'standards.matrix.title': 'Star Level Matrix',
    'standards.matrix.description': 'Comparison of standard requirements based on certification levels',
    'standards.matrix.criteria': 'Assessment Criteria',
    'standards.matrix.one': 'One Star',
    'standards.matrix.two': 'Two Star',
    'standards.matrix.three': 'Three Star',
    'standards.matrix.prayer': 'Prayer Room Provision',
    'standards.matrix.prayer.one': 'Required (Available)',
    'standards.matrix.prayer.two': 'Required (Spacious & Comfortable)',
    'standards.matrix.prayer.three': 'Exclusive (Premium Facilities)',
    'standards.matrix.menu': 'Halal Menu',
    'standards.matrix.menu.one': 'Minimum 50% Menu',
    'standards.matrix.menu.two': 'Minimum 75% Menu',
    'standards.matrix.menu.three': '100% Halal Certified',
    'standards.matrix.toilet': 'Muslim-Friendly Toilet',
    'standards.matrix.toilet.one': 'Meets General Standards',
    'standards.matrix.toilet.two': 'Complete Istinja Equipment',
    'standards.matrix.toilet.three': 'Advanced Sanitation System',
    'standards.matrix.hygiene': 'Has Hygiene Eligibility Certificate',
    'standards.matrix.hygiene.one': 'Optional',
    'standards.matrix.hygiene.two': 'Recommended',
    'standards.matrix.hygiene.three': 'Required',
    'standards.documents.title': 'Reference Documents',
    'standards.documents.description': 'Download operational standard documents and technical procedures for MFTC certification preparation.',
    'standards.documents.viewAll': 'View All Archives',
    'standards.documents.standard.title': 'MFTC Standards 2025',
    'standards.documents.standard.subtitle': 'Main Guide for New Certification Criteria',
    'standards.documents.procedure.title': 'PO/HALAL-PPS/04',
    'standards.documents.procedure.subtitle': 'Halal Assurance Operational Procedure',
    'standards.documents.self.title': 'Self-Assessment Form',
    'standards.documents.self.subtitle': 'Internal Audit Preparation Document',
    'standards.documents.hygiene.title': 'Hygiene Guide 2.0',
    'standards.documents.hygiene.subtitle': 'Thaharah Sanitation Standards for Hotels',
    'pricing.badge': 'Transparent & Trusted',
    'pricing.hero.title': 'Investment for Excellence',
    'pricing.hero.highlight': 'Muslim Friendly Tourism',
    'pricing.hero.description': 'A professionally designed fee structure that reflects globally recognized international certification standards.',
    'pricing.card.badge': 'Certification Package',
    'pricing.card.title': 'MFTC Certification',
    'pricing.card.description': 'Official Muslim Friendly Tourism Certification by Sucofindo International Certification Services.',
    'pricing.card.starting': 'Starting from',
    'pricing.card.currency': 'IDR',
    'pricing.card.price': '6.5M',
    'pricing.card.tax': 'Excluding 11% VAT',
    'pricing.card.start': 'Start Certification',
    'pricing.card.learn': 'Learn More',
    'pricing.included.title': 'What Is Included',
    'pricing.included.description': 'Each application includes a comprehensive two-stage audit service according to Muslim Friendly Tourism Standards.',
    'pricing.feature.audit.title': 'Two-Stage Audit',
    'pricing.feature.audit.desc': 'Stage I audit (documents) and Stage II audit (site visit) by certified auditors.',
    'pricing.feature.certificate.title': 'Official MFTC Certificate',
    'pricing.feature.certificate.desc': 'Certificate valid for 5 years, issued by Sucofindo International Certification Services.',
    'pricing.feature.assist.title': 'Process Assistance',
    'pricing.feature.assist.desc': 'Our Sales and Auditor teams assist the full process from application to certificate issuance.',
    'pricing.feature.multi.title': 'Flexible Multi-Location',
    'pricing.feature.multi.desc': 'Mandays are adjusted based on the number of locations and submitted scope.',
    'pricing.feature.international.title': 'International Service',
    'pricing.feature.international.desc': 'Auditor travel allowance can be adjusted for overseas clients.',
    'pricing.notes.title': 'Cost Information',
    'pricing.notes.vat': 'The listed fee excludes 11% VAT.',
    'pricing.notes.mandays': 'Mandays are determined based on the number of locations and submitted scope.',
    'pricing.notes.initial': 'This fee applies to initial certification and does not include annual surveillance fees.',
    'pricing.notes.travel': 'Auditor travel allowance can be adjusted for overseas assignments.',
    'pricing.badge.international.title': 'Internationally Recognized',
    'pricing.badge.international.desc': 'MFTC standards are recognized by international tourism institutions.',
    'pricing.badge.consult.title': 'Free Consultation',
    'pricing.badge.consult.desc': 'Our team is ready to guide you before starting the certification process.',
    'pricing.badge.transparent.title': 'Transparent Pricing',
    'pricing.badge.transparent.desc': 'No hidden fees. All cost components are communicated upfront.',
    'pricing.cta.question': 'Need a special enterprise-scale proposal?',
    'pricing.cta.link': 'Contact our team →',
    'about.hero.badge': 'Pioneer of Global Standardization',
    'about.hero.title': 'About MFTC: Elevating Indonesian Muslim Tourism Standards Globally',
    'about.hero.standards': 'Explore Our Standards',
    'about.hero.contact': 'Contact Expert Team',
    'about.stats.partners': 'Certified Partners',
    'about.stats.provinces': 'Provinces Reached',
    'about.stats.compliance': 'Sharia Compliance',
    'about.mission.title': 'Our Mission for Indonesia',
    'about.mission.description': 'Muslim-Friendly Tourism Certification (MFTC) was born from a major vision to make Indonesia the center of global halal tourism. We bridge the gap between local tourism potential and global Muslim traveler expectations through credible and measurable standardization.',
    'about.accreditation.title': 'Trusted Accreditation',
    'about.accreditation.description': 'Every certificate we issue is the result of strict audits referring to DSN-MUI fatwas and global halal tourism standards.',
    'about.values.badge': 'Foundational Pillars',
    'about.values.title': 'Our Core Values',
    'about.values.integrity.title': 'Integrity',
    'about.values.integrity.description': 'We uphold honesty in every verification process, ensuring full transparency for all stakeholders in the tourism ecosystem.',
    'about.values.professional.title': 'Professionalism',
    'about.values.professional.description': 'Supported by certified auditors and industry experts, we deliver certification services with best-in-class operational standards.',
    'about.values.sharia.title': 'Sharia Compliance',
    'about.values.sharia.description': 'Every assessment indicator aligns with Islamic values, ensuring worship comfort and halal consumption for travelers.',
    'about.partner.badge': 'Official Partner',
    'about.partner.title': 'Strategic Collaboration with PT Sucofindo',
    'about.partner.description': 'MFTC has an exclusive partnership with PT Sucofindo as the official certification body. This synergy combines decades of Sucofindo technical audit expertise with MFTC specialization in Muslim-friendly standards.',
    'about.partner.audit': 'Independent & Objective Audit',
    'about.partner.recognition': 'National & International Recognition',
    'about.partner.digital': 'Integrated Digital System Process',
    'about.partner.body': 'Official Certifying Body',
  },
  zh: {
    'common.loading': '加载中...',
    'common.login': '登录',
    'common.register': '注册',
    'common.dashboard': '仪表板',
    'common.language': '语言',
    'auth.brand.login': 'MFT Certify',
    'auth.brand.register': 'HalalCertify',
    'auth.portal': 'MFTC 门户',
    'auth.login.hero.title': '通过全球清真认证建立信任。',
    'auth.login.hero.description': '访问管理门户，监控您的穆斯林友好旅游标准、申请和合规情况。',
    'auth.login.globalReach': '全球覆盖',
    'auth.login.certifiedRegions': '认证地区',
    'auth.login.reliability': '可靠性',
    'auth.login.complianceRate': '合规率',
    'auth.login.title': '登录 MFT 门户',
    'auth.login.subtitle': '安全管理您的穆斯林友好旅游认证。',
    'auth.login.email': '电子邮箱',
    'auth.login.emailPlaceholder': 'name@company.com',
    'auth.login.password': '密码',
    'auth.login.forgot': '忘记密码？',
    'auth.login.remember': '保持登录 30 天',
    'auth.login.submit': '立即登录',
    'auth.login.processing': '处理中…',
    'auth.login.or': '或使用以下方式登录',
    'auth.login.google': '使用 Google 登录',
    'auth.login.noAccount': '还没有账号？',
    'auth.login.registerLink': '注册认证',
    'auth.login.failed': '登录失败。请重试。',
    'auth.register.badge': '可信赖的认证入门流程',
    'auth.register.hero.title': '提升穆斯林友好旅游的全球标准。',
    'auth.register.hero.description': '加入旅游服务商，通过有指导、安全且透明的数字流程完成穆斯林友好旅游认证。',
    'auth.register.stat.partners': '认证伙伴',
    'auth.register.stat.countries': '国家',
    'auth.register.stat.integrity': '诚信率',
    'auth.register.role': '企业用户',
    'auth.register.title': '创建 MFTC 账号',
    'auth.register.subtitle': '填写以下资料，以企业用户（PU）身份开始您的认证流程。',
    'auth.register.fullName': '姓名',
    'auth.register.fullNamePlaceholder': '例如：Ahmad Abdullah',
    'auth.register.email': '企业邮箱',
    'auth.register.phone': '电话 / WhatsApp 号码',
    'auth.register.password': '密码',
    'auth.register.passwordPlaceholder': '至少 8 个字符',
    'auth.register.passwordHelp': '至少 8 个字符，并包含字母和数字组合。',
    'auth.register.confirmPassword': '确认密码',
    'auth.register.confirmPasswordPlaceholder': '再次输入密码',
    'auth.register.termsPrefix': '我同意',
    'auth.register.terms': '条款与条件',
    'auth.register.privacyPrefix': '以及',
    'auth.register.privacy': '隐私政策',
    'auth.register.termsSuffix': 'MFTC。',
    'auth.register.submit': '立即注册',
    'auth.register.submitting': '注册中...',
    'auth.register.haveAccount': '已有账号？',
    'auth.register.loginLink': '在此登录',
    'auth.register.failed': '注册失败。请重试。',
    'auth.validation.email': '邮箱无效。',
    'auth.validation.passwordMin': '密码至少 8 个字符。',
    'auth.validation.fullNameRequired': '姓名为必填项',
    'auth.validation.emailInvalid': '邮箱格式无效',
    'auth.validation.passwordRegisterMin': '至少 8 个字符',
    'auth.validation.passwordCombination': '必须包含字母和数字',
    'auth.validation.terms': '您必须同意条款与条件',
    'auth.validation.passwordConfirmation': '两次输入的密码不一致',
    'auth.password.hide': '隐藏密码',
    'auth.password.show': '显示密码',
    'auth.password.hideConfirm': '隐藏确认密码',
    'auth.password.showConfirm': '显示确认密码',
    'public.nav.home': '首页',
    'public.nav.standards': '标准',
    'public.nav.pricing': '价格',
    'public.nav.about': '关于',
    'public.footer.links': '链接',
    'public.footer.about': '关于 MFTC',
    'public.footer.standards': '标准',
    'public.footer.verify': '证书验证',
    'public.footer.follow': '关注我们',
    'public.footer.description': '推动全球旅游业转型，打造包容、尊重且经过认证的穆斯林友好生态系统。',
    'public.footer.privacy': '隐私政策',
    'public.footer.terms': '服务条款',
    'public.footer.support': '联系支持',
    Page: '第',
    of: '页，共',
    Total: '总计',
    'pu.title': 'PU 仪表板',
    'pu.sidebar.dashboard': '仪表板',
    'pu.sidebar.profile': '企业资料',
    'pu.sidebar.applications': '申请',
    'pu.sidebar.certificates': '证书',
    'pu.sidebar.help': '帮助中心',
    'pu.logout': '退出登录',
    'pu.logout.loading': '正在退出…',
    'notifications.title': '通知',
    'notifications.subtitle': 'LPH 团队的最新活动',
    'notifications.empty': '暂无最新活动。',
    'landing.badge': '全球卓越标准',
    'landing.hero.title': '将穆斯林友好旅游提升至全球标准',
    'landing.hero.description': '穆斯林友好旅游认证（MFTC）提供全面框架，确保全球穆斯林旅游市场的诚信、质量与热情服务。',
    'landing.hero.start': '开始认证',
    'landing.hero.standards': '查看标准',
    'landing.iso.title': '符合 ISO 标准',
    'landing.iso.subtitle': '国际标准',
    'landing.levels.title': '认证等级',
    'landing.levels.description': '可扩展标准，用于认可并提升全球穆斯林友好服务质量。',
    'landing.level.one.title': '一星',
    'landing.level.one.label': '基础等级',
    'landing.level.one.description': '入门级认证，重点关注基本祈祷设施和清真食品可及性要求。',
    'landing.level.two.title': '二星',
    'landing.level.two.label': '中级卓越',
    'landing.level.two.description': '高级认证，包括专业接待人员培训和增强的设施隐私功能。',
    'landing.level.three.title': '三星',
    'landing.level.three.label': '高级认可',
    'landing.level.three.description': '高端穆斯林友好奢华、完整生态整合和世界级服务的黄金标准。',
    'landing.scope.title': '认证范围',
    'landing.scope.description': '我们为整个旅游价值链提供专业审核和认证服务。',
    'landing.scope.viewAll': '查看全部范围',
    'landing.scope.hotel': '酒店',
    'landing.scope.restaurant': '餐厅',
    'landing.scope.travelAgent': '旅行社',
    'landing.scope.attractions': '景点',
    'landing.scope.shopping': '购物',
    'landing.scope.transport': '交通',
    'landing.scope.medical': '医疗',
    'landing.scope.events': '活动',
    'landing.scope.holySites': '宗教圣地',
    'landing.scope.consultancy': '咨询',
    'landing.stats.partners': '认证合作伙伴',
    'landing.stats.countries': '国家',
    'landing.stats.rooms': '已审核客房',
    'landing.stats.integrity': '诚信率',
    'standards.badge': '2025 官方指南',
    'standards.hero.title': '穆斯林友好旅游标准（MFTC）',
    'standards.hero.description': '提升印尼穆斯林友好旅游服务标准的综合参考，确保舒适、信任与全球合规。',
    'standards.hero.criteria': '了解标准',
    'standards.hero.download': '下载文件',
    'standards.criteria.title': '主要标准',
    'standards.criteria.prayer.title': '祈祷设施',
    'standards.criteria.prayer.description': '提供清洁的祈祷室、准确的朝拜方向，以及充足且分开的净礼设施。',
    'standards.criteria.food.title': '清真食品',
    'standards.criteria.food.description': '确保食品和饮料从原料到上桌的全过程均符合清真认证。',
    'standards.criteria.service.title': '通用服务',
    'standards.criteria.service.description': '员工接受穆斯林友好服务礼仪培训，并深入理解客人需求。',
    'standards.criteria.sanitation.title': '卫生与清洁',
    'standards.criteria.sanitation.description': '公共区域和卫生间执行严格清洁标准，支持 Thaharah 洁净概念。',
    'standards.matrix.title': '星级矩阵',
    'standards.matrix.description': '按认证等级比较标准要求',
    'standards.matrix.criteria': '评估标准',
    'standards.matrix.one': '一星',
    'standards.matrix.two': '二星',
    'standards.matrix.three': '三星',
    'standards.matrix.prayer': '祈祷室提供',
    'standards.matrix.prayer.one': '必需（可用）',
    'standards.matrix.prayer.two': '必需（宽敞舒适）',
    'standards.matrix.prayer.three': '专属（高级设施）',
    'standards.matrix.menu': '清真菜单',
    'standards.matrix.menu.one': '至少 50% 菜单',
    'standards.matrix.menu.two': '至少 75% 菜单',
    'standards.matrix.menu.three': '100% 清真认证',
    'standards.matrix.toilet': '穆斯林友好卫生间',
    'standards.matrix.toilet.one': '符合通用标准',
    'standards.matrix.toilet.two': '完整净洗设备',
    'standards.matrix.toilet.three': '先进卫生系统',
    'standards.matrix.hygiene': '拥有卫生合格证书',
    'standards.matrix.hygiene.one': '可选',
    'standards.matrix.hygiene.two': '推荐',
    'standards.matrix.hygiene.three': '必需',
    'standards.documents.title': '参考文件',
    'standards.documents.description': '下载 MFTC 认证准备所需的操作标准文件和技术程序。',
    'standards.documents.viewAll': '查看所有档案',
    'standards.documents.standard.title': 'MFTC 标准 2025',
    'standards.documents.standard.subtitle': '新认证标准主要指南',
    'standards.documents.procedure.title': 'PO/HALAL-PPS/04',
    'standards.documents.procedure.subtitle': '清真保障操作程序',
    'standards.documents.self.title': '自评表',
    'standards.documents.self.subtitle': '内部审核准备文件',
    'standards.documents.hygiene.title': '卫生指南 2.0',
    'standards.documents.hygiene.subtitle': '酒店 Thaharah 卫生标准',
    'pricing.badge': '透明可信',
    'pricing.hero.title': '卓越投资',
    'pricing.hero.highlight': '穆斯林友好旅游',
    'pricing.hero.description': '专业设计的费用结构，体现全球认可的国际认证标准。',
    'pricing.card.badge': '认证套餐',
    'pricing.card.title': 'MFTC 认证',
    'pricing.card.description': '由 Sucofindo International Certification Services 提供的官方穆斯林友好旅游认证。',
    'pricing.card.starting': '起价',
    'pricing.card.currency': '印尼盾',
    'pricing.card.price': '650万',
    'pricing.card.tax': '不含 11% 增值税',
    'pricing.card.start': '开始认证',
    'pricing.card.learn': '了解更多',
    'pricing.included.title': '费用包含内容',
    'pricing.included.description': '每项申请均包含符合穆斯林友好旅游标准的两阶段综合审核服务。',
    'pricing.feature.audit.title': '两阶段审核',
    'pricing.feature.audit.desc': '由认证审核员执行第一阶段（文件）和第二阶段（现场访问）审核。',
    'pricing.feature.certificate.title': '官方 MFTC 证书',
    'pricing.feature.certificate.desc': '证书有效期 5 年，由 Sucofindo International Certification Services 签发。',
    'pricing.feature.assist.title': '流程协助',
    'pricing.feature.assist.desc': '我们的销售和审核团队将协助从申请到证书签发的整个流程。',
    'pricing.feature.multi.title': '灵活多地点',
    'pricing.feature.multi.desc': '审核人天数将根据提交的地点数量和认证范围进行调整。',
    'pricing.feature.international.title': '国际服务',
    'pricing.feature.international.desc': '海外客户的审核员差旅津贴可按需求调整。',
    'pricing.notes.title': '费用信息',
    'pricing.notes.vat': '所列费用不含 11% 增值税。',
    'pricing.notes.mandays': '审核人天数根据提交的地点数量和认证范围确定。',
    'pricing.notes.initial': '此费用适用于初次认证，不包含年度监督审核费用。',
    'pricing.notes.travel': '海外任务的审核员差旅津贴可进行调整。',
    'pricing.badge.international.title': '国际认可',
    'pricing.badge.international.desc': 'MFTC 标准获得国际旅游机构认可。',
    'pricing.badge.consult.title': '免费咨询',
    'pricing.badge.consult.desc': '我们的团队将在您开始认证流程前提供指导。',
    'pricing.badge.transparent.title': '价格透明',
    'pricing.badge.transparent.desc': '无隐藏费用。所有费用组成均会提前说明。',
    'pricing.cta.question': '需要企业级特殊报价？',
    'pricing.cta.link': '联系我们的团队 →',
    'about.hero.badge': '全球标准化先驱',
    'about.hero.title': '关于 MFTC：将印尼穆斯林旅游标准提升至全球水平',
    'about.hero.standards': '了解我们的标准',
    'about.hero.contact': '联系专家团队',
    'about.stats.partners': '认证合作伙伴',
    'about.stats.provinces': '覆盖省份',
    'about.stats.compliance': '伊斯兰合规',
    'about.mission.title': '我们对印尼的使命',
    'about.mission.description': '穆斯林友好旅游认证（MFTC）源于让印尼成为全球清真旅游中心的宏大愿景。我们通过可信且可衡量的标准化，连接本地旅游潜力与全球穆斯林游客期望。',
    'about.accreditation.title': '可信认证',
    'about.accreditation.description': '我们签发的每一份证书都源于严格审核，并参考 DSN-MUI 法令和全球清真旅游标准。',
    'about.values.badge': '核心支柱',
    'about.values.title': '我们的核心价值',
    'about.values.integrity.title': '诚信',
    'about.values.integrity.description': '我们在每个验证流程中坚持诚实，确保旅游生态系统中所有利益相关者完全透明。',
    'about.values.professional.title': '专业精神',
    'about.values.professional.description': '在认证审核员和行业专家支持下，我们以一流运营标准提供认证服务。',
    'about.values.sharia.title': '伊斯兰合规',
    'about.values.sharia.description': '我们的每项评估指标均符合伊斯兰价值，确保游客礼拜舒适与清真消费。',
    'about.partner.badge': '官方合作伙伴',
    'about.partner.title': '与 PT Sucofindo 的战略合作',
    'about.partner.description': 'MFTC 与 PT Sucofindo 建立独家合作，作为官方认证机构。该协同结合了 Sucofindo 数十年的技术审核经验与 MFTC 在穆斯林友好标准方面的专业能力。',
    'about.partner.audit': '独立客观审核',
    'about.partner.recognition': '国家与国际认可',
    'about.partner.digital': '数字系统集成流程',
    'about.partner.body': '官方认证机构',
  },
}

const phraseTranslations: Record<string, { en: string; zh: string }> = {
  'Global Standard for Excellence': { en: 'Global Standard for Excellence', zh: '全球卓越标准' },
  'Elevating Muslim Friendly Tourism to Global Standards': { en: 'Elevating Muslim Friendly Tourism to Global Standards', zh: '将穆斯林友好旅游提升至全球标准' },
  'The Muslim Friendly Tourism Certification (MFTC) provides a comprehensive framework to ensure integrity, quality, and hospitality for the global Muslim travel market.': { en: 'The Muslim Friendly Tourism Certification (MFTC) provides a comprehensive framework to ensure integrity, quality, and hospitality for the global Muslim travel market.', zh: '穆斯林友好旅游认证（MFTC）提供全面框架，确保全球穆斯林旅游市场的诚信、质量与热情服务。' },
  'Start Certification': { en: 'Start Certification', zh: '开始认证' },
  'View Standards': { en: 'View Standards', zh: '查看标准' },
  'ISO Compliant': { en: 'ISO Compliant', zh: '符合 ISO 标准' },
  'International Standards': { en: 'International Standards', zh: '国际标准' },
  'Certification Levels': { en: 'Certification Levels', zh: '认证等级' },
  'Certification Scope': { en: 'Certification Scope', zh: '认证范围' },
  'View All Scopes': { en: 'View All Scopes', zh: '查看全部范围' },
  'Certified Partners': { en: 'Certified Partners', zh: '认证合作伙伴' },
  Countries: { en: 'Countries', zh: '国家' },
  'Audited Rooms': { en: 'Audited Rooms', zh: '已审核客房' },
  'Integrity Rate': { en: 'Integrity Rate', zh: '诚信率' },
  Hotel: { en: 'Hotel', zh: '酒店' },
  Restaurant: { en: 'Restaurant', zh: '餐厅' },
  'Travel Agent': { en: 'Travel Agent', zh: '旅行社' },
  Attractions: { en: 'Attractions', zh: '景点' },
  Shopping: { en: 'Shopping', zh: '购物' },
  Transport: { en: 'Transport', zh: '交通' },
  Medical: { en: 'Medical', zh: '医疗' },
  Events: { en: 'Events', zh: '活动' },
  'Holy Sites': { en: 'Holy Sites', zh: '宗教圣地' },
  Consultancy: { en: 'Consultancy', zh: '咨询' },
  'Pelopor Standarisasi Global': { en: 'Pioneer of Global Standardization', zh: '全球标准化先驱' },
  'Tentang MFTC: Mengangkat Standar Pariwisata Muslim Indonesia ke Tingkat Global': { en: 'About MFTC: Elevating Indonesian Muslim Tourism Standards Globally', zh: '关于 MFTC：将印尼穆斯林旅游标准提升至全球水平' },
  'Pelajari Standar Kami': { en: 'Explore Our Standards', zh: '了解我们的标准' },
  'Hubungi Tim Ahli': { en: 'Contact Expert Team', zh: '联系专家团队' },
  'Misi Kami untuk Indonesia': { en: 'Our Mission for Indonesia', zh: '我们对印尼的使命' },
  'Nilai-Nilai Utama Kami': { en: 'Our Core Values', zh: '我们的核心价值' },
  Integritas: { en: 'Integrity', zh: '诚信' },
  Profesionalisme: { en: 'Professionalism', zh: '专业精神' },
  'Kepatuhan Syariah': { en: 'Sharia Compliance', zh: '伊斯兰合规' },
  'Kolaborasi Strategis dengan PT Sucofindo': { en: 'Strategic Collaboration with PT Sucofindo', zh: '与 PT Sucofindo 的战略合作' },
  'Audit Independen & Objektif': { en: 'Independent & Objective Audit', zh: '独立客观审核' },
  'Pengakuan Nasional & Internasional': { en: 'National & International Recognition', zh: '国家与国际认可' },
  'Proses Terintegrasi Sistem Digital': { en: 'Integrated Digital System Process', zh: '数字系统集成流程' },
  'Transparan & Terpercaya': { en: 'Transparent & Trusted', zh: '透明可信' },
  'Investasi untuk Keunggulan': { en: 'Investment for Excellence', zh: '卓越投资' },
  'Muslim Friendly Tourism': { en: 'Muslim Friendly Tourism', zh: '穆斯林友好旅游' },
  'Paket Sertifikasi': { en: 'Certification Package', zh: '认证套餐' },
  'Sertifikasi MFTC': { en: 'MFTC Certification', zh: 'MFTC 认证' },
  'Mulai dari': { en: 'Starting from', zh: '起价' },
  'Belum termasuk PPN 11%': { en: 'Excluding 11% VAT', zh: '不含 11% 增值税' },
  'Mulai Sertifikasi': { en: 'Start Certification', zh: '开始认证' },
  'Pelajari Lebih Lanjut': { en: 'Learn More', zh: '了解更多' },
  'Yang Tercakup dalam Biaya': { en: 'What Is Included', zh: '费用包含内容' },
  'Audit Dua Tahap': { en: 'Two-Stage Audit', zh: '两阶段审核' },
  'Sertifikat Resmi MFTC': { en: 'Official MFTC Certificate', zh: '官方 MFTC 证书' },
  'Pendampingan Proses': { en: 'Process Assistance', zh: '流程协助' },
  'Fleksibel Multi-Lokasi': { en: 'Flexible Multi-Location', zh: '灵活多地点' },
  'Layanan Internasional': { en: 'International Service', zh: '国际服务' },
  'Informasi Biaya': { en: 'Cost Information', zh: '费用信息' },
  'Diakui Internasional': { en: 'Internationally Recognized', zh: '国际认可' },
  'Konsultasi Gratis': { en: 'Free Consultation', zh: '免费咨询' },
  'Harga Transparan': { en: 'Transparent Pricing', zh: '价格透明' },
  'Panduan Resmi 2025': { en: 'Official 2025 Guide', zh: '2025 官方指南' },
  'Standar Pariwisata Ramah Muslim (MFTC)': { en: 'Muslim Friendly Tourism Standards (MFTC)', zh: '穆斯林友好旅游标准（MFTC）' },
  'Pelajari Kriteria': { en: 'Explore Criteria', zh: '了解标准' },
  'Unduh Dokumen': { en: 'Download Document', zh: '下载文件' },
  'Kriteria Utama': { en: 'Main Criteria', zh: '主要标准' },
  'Matriks Level Bintang': { en: 'Star Level Matrix', zh: '星级矩阵' },
  'Kriteria Penilaian': { en: 'Assessment Criteria', zh: '评估标准' },
  'Dokumen Acuan': { en: 'Reference Documents', zh: '参考文件' },
  'Lihat Semua Arsip': { en: 'View All Archives', zh: '查看所有档案' },
  'Masuk ke MFT Portal': { en: 'Sign in to MFT Portal', zh: '登录 MFT 门户' },
  'Alamat Email': { en: 'Email Address', zh: '电子邮箱' },
  'Kata Sandi': { en: 'Password', zh: '密码' },
  'Lupa sandi?': { en: 'Forgot password?', zh: '忘记密码？' },
  'Tetap masuk selama 30 hari': { en: 'Stay signed in for 30 days', zh: '保持登录 30 天' },
  'Masuk Sekarang': { en: 'Sign In Now', zh: '立即登录' },
  'Memproses…': { en: 'Processing…', zh: '处理中…' },
  'Atau masuk dengan': { en: 'Or sign in with', zh: '或使用以下方式登录' },
  'Masuk dengan Google': { en: 'Sign in with Google', zh: '使用 Google 登录' },
  'Belum punya akun?': { en: "Don't have an account?", zh: '还没有账户？' },
  'Daftar Sertifikasi': { en: 'Register for Certification', zh: '注册认证' },
  'Daftar Akun MFTC': { en: 'Register MFTC Account', zh: '注册 MFTC 账户' },
  'Nama Lengkap': { en: 'Full Name', zh: '全名' },
  'Email Bisnis': { en: 'Business Email', zh: '商务邮箱' },
  'Nomor Telepon / WhatsApp': { en: 'Phone / WhatsApp Number', zh: '电话 / WhatsApp 号码' },
  'Konfirmasi Kata Sandi': { en: 'Confirm Password', zh: '确认密码' },
  'Daftar Sekarang': { en: 'Register Now', zh: '立即注册' },
  'Sudah memiliki akun?': { en: 'Already have an account?', zh: '已有账户？' },
  'Login di sini': { en: 'Login here', zh: '在此登录' },
  'Verifikasi Sertifikat': { en: 'Certificate Verification', zh: '证书验证' },
  'Nomor Sertifikat': { en: 'Certificate Number', zh: '证书编号' },
  Verifikasi: { en: 'Verify', zh: '验证' },
  'Sertifikat Terverifikasi': { en: 'Certificate Verified', zh: '证书已验证' },
  Level: { en: 'Level', zh: '等级' },
  'Tanggal Terbit': { en: 'Issue Date', zh: '签发日期' },
  'Berlaku Hingga': { en: 'Valid Until', zh: '有效期至' },
  'Total Applications': { en: 'Total Applications', zh: '申请总数' },
  'Active Certificates': { en: 'Active Certificates', zh: '有效证书' },
  'Action Required': { en: 'Action Required', zh: '需要操作' },
  'Latest Progress': { en: 'Latest Progress', zh: '最新进展' },
  'Recent Applications': { en: 'Recent Applications', zh: '最近申请' },
  'Grow your business with Halal Excellence': { en: 'Grow your business with Halal Excellence', zh: '以清真卓越推动业务增长' },
  'View Details': { en: 'View Details', zh: '查看详情' },
  'View All': { en: 'View All', zh: '查看全部' },
  Review: { en: 'Review', zh: '审核' },
  'Access Toolkit': { en: 'Access Toolkit', zh: '访问工具包' },
  'Belum ada pengajuan.': { en: 'No applications yet.', zh: '暂无申请。' },
  'Belum ada pengajuan aktif.': { en: 'No active applications yet.', zh: '暂无有效申请。' },
  'Daftar Pengajuan': { en: 'Application List', zh: '申请列表' },
  'Pengajuan Baru': { en: 'New Application', zh: '新申请' },
  'Filter Status': { en: 'Filter Status', zh: '筛选状态' },
  'Semua Status': { en: 'All Statuses', zh: '全部状态' },
  'ID Pengajuan': { en: 'Application ID', zh: '申请编号' },
  Tanggal: { en: 'Date', zh: '日期' },
  Scope: { en: 'Scope', zh: '范围' },
  Status: { en: 'Status', zh: '状态' },
  Aksi: { en: 'Action', zh: '操作' },
  Tinjau: { en: 'Review', zh: '查看' },
  'Tidak ada data pengajuan.': { en: 'No application data.', zh: '暂无申请数据。' },
  'Memuat pengajuan…': { en: 'Loading applications…', zh: '正在加载申请…' },
  Sebelumnya: { en: 'Previous', zh: '上一页' },
  Berikutnya: { en: 'Next', zh: '下一页' },
  'Profil Usaha': { en: 'Business Profile', zh: '企业资料' },
  'Profil Lengkap': { en: 'Profile Complete', zh: '资料完整' },
  'Perlu Dilengkapi': { en: 'Needs Completion', zh: '需要完善' },
  'Biodata Usaha': { en: 'Business Information', zh: '企业信息' },
  'Wajib Diisi': { en: 'Required', zh: '必填' },
  'NAMA PERUSAHAAN': { en: 'COMPANY NAME', zh: '公司名称' },
  'PERSONIL PENGHUBUNG': { en: 'CONTACT PERSON', zh: '联系人' },
  'NOMOR INDUK BERUSAHA (NIB)': { en: 'BUSINESS IDENTIFICATION NUMBER (NIB)', zh: '企业识别号（NIB）' },
  'ALAMAT LENGKAP': { en: 'FULL ADDRESS', zh: '完整地址' },
  'Pilih File': { en: 'Choose File', zh: '选择文件' },
  'Ganti File': { en: 'Replace File', zh: '更换文件' },
  'Lanjut Buat Pengajuan': { en: 'Continue to Create Application', zh: '继续创建申请' },
  'Simpan Profil': { en: 'Save Profile', zh: '保存资料' },
  'Menyimpan…': { en: 'Saving…', zh: '保存中…' },
  'Data Terenkripsi': { en: 'Encrypted Data', zh: '数据已加密' },
  'Hapus Akun': { en: 'Delete Account', zh: '删除账户' },
  Batal: { en: 'Cancel', zh: '取消' },
  'Ya, Hapus Akun': { en: 'Yes, Delete Account', zh: '是，删除账户' },
  'Kembali ke Daftar Pengajuan': { en: 'Back to Applications', zh: '返回申请列表' },
  'Versi data:': { en: 'Data version:', zh: '数据版本：' },
  'Progress Pengajuan': { en: 'Application Progress', zh: '申请进度' },
  'Pembayaran Invoice': { en: 'Invoice Payment', zh: '发票付款' },
  'Menunggu Pembayaran': { en: 'Waiting for Payment', zh: '等待付款' },
  'No. Invoice': { en: 'Invoice No.', zh: '发票编号' },
  'Jumlah Tagihan': { en: 'Amount Due', zh: '应付金额' },
  'Jatuh Tempo': { en: 'Due Date', zh: '截止日期' },
  'Rekening Tujuan': { en: 'Destination Account', zh: '收款账户' },
  'Upload Bukti Pembayaran': { en: 'Upload Payment Proof', zh: '上传付款凭证' },
  'Pembayaran terverifikasi': { en: 'Payment verified', zh: '付款已验证' },
  'Konfirmasi Jadwal Audit': { en: 'Confirm Audit Schedule', zh: '确认审核日程' },
  Auditor: { en: 'Auditor', zh: '审核员' },
  'Tanggal Audit': { en: 'Audit Date', zh: '审核日期' },
  'Waktu Mulai': { en: 'Start Time', zh: '开始时间' },
  'Lokasi Audit': { en: 'Audit Location', zh: '审核地点' },
  'Minta Reschedule': { en: 'Request Reschedule', zh: '申请改期' },
  'Konfirmasi Jadwal': { en: 'Confirm Schedule', zh: '确认日程' },
  'Alasan Reschedule': { en: 'Reschedule Reason', zh: '改期原因' },
  'Kirim Permintaan': { en: 'Send Request', zh: '发送请求' },
  'Jadwal audit telah dikonfirmasi': { en: 'Audit schedule confirmed', zh: '审核日程已确认' },
  'Audit sedang berlangsung': { en: 'Audit in progress', zh: '审核进行中' },
  'Terdapat Ketidaksesuaian': { en: 'Non-Conformity Found', zh: '发现不符合项' },
  'Lihat & Perbaiki Non-Conformity': { en: 'View & Fix Non-Conformity', zh: '查看并修正不符合项' },
  'Laporan audit menunggu persetujuan': { en: 'Audit report awaiting approval', zh: '审核报告等待批准' },
  'Sertifikat Telah Terbit': { en: 'Certificate Issued', zh: '证书已签发' },
  Diterbitkan: { en: 'Issued', zh: '已签发' },
  'Buka Sertifikat': { en: 'Open Certificate', zh: '打开证书' },
  'Pengajuan tidak aktif': { en: 'Application inactive', zh: '申请未激活' },
  'Lokasi Usaha': { en: 'Business Locations', zh: '营业地点' },
  'Sertifikat Halal Tourism': { en: 'Halal Tourism Certificates', zh: '清真旅游证书' },
  'Belum ada sertifikat': { en: 'No certificates yet', zh: '暂无证书' },
  Aktif: { en: 'Active', zh: '有效' },
  Kedaluwarsa: { en: 'Expired', zh: '已过期' },
  'Download PDF': { en: 'Download PDF', zh: '下载 PDF' },
  'PDF Belum Tersedia': { en: 'PDF Not Available', zh: 'PDF 暂不可用' },
  'Ruang Lingkup': { en: 'Scope', zh: '范围' },
  'Lokasi Multisitus': { en: 'Multi-Site Locations', zh: '多地点位置' },
  'Pra-Assessment': { en: 'Pre-Assessment', zh: '预评估' },
  Wajib: { en: 'Required', zh: '必填' },
  'Tambah File': { en: 'Add File', zh: '添加文件' },
  'Tulis jawaban Anda': { en: 'Write your answer', zh: '填写您的答案' },
  'Pilih jawaban': { en: 'Select an answer', zh: '选择答案' },
  'Tarik file ke sini atau klik untuk pilih': { en: 'Drag file here or click to select', zh: '将文件拖到此处或点击选择' },
  Hapus: { en: 'Delete', zh: '删除' },
  Reset: { en: 'Reset', zh: '重置' },
  'Kirim Bukti Bayar': { en: 'Submit Payment Proof', zh: '提交付款凭证' },
  'Entry-level certification focused on essential prayer facilities and halal food accessibility requirements.': { en: 'Entry-level certification focused on essential prayer facilities and halal food accessibility requirements.', zh: '入门级认证，重点关注基本祈祷设施和清真食品可及性要求。' },
  'Advanced certification including specialized hospitality staff training and enhanced facility privacy features.': { en: 'Advanced certification including specialized hospitality staff training and enhanced facility privacy features.', zh: '高级认证，包括专业接待人员培训和增强的设施隐私功能。' },
  'The gold standard for premium Muslim-friendly luxury, full eco-system integration, and world-class service.': { en: 'The gold standard for premium Muslim-friendly luxury, full eco-system integration, and world-class service.', zh: '高端穆斯林友好奢华、完整生态整合和世界级服务的黄金标准。' },
  'Scalable standards designed to recognize and improve the quality of Muslim-friendly services globally.': { en: 'Scalable standards designed to recognize and improve the quality of Muslim-friendly services globally.', zh: '可扩展标准，用于认可并提升全球穆斯林友好服务质量。' },
  'We provide specialized auditing and certification services across the entire tourism value chain.': { en: 'We provide specialized auditing and certification services across the entire tourism value chain.', zh: '我们为整个旅游价值链提供专业审核和认证服务。' },
  'Akses portal manajemen untuk memantau standar, aplikasi, dan kepatuhan pariwisata ramah Muslim Anda.': { en: 'Access the management portal to monitor your Muslim-friendly tourism standards, applications, and compliance.', zh: '访问管理门户，监控您的穆斯林友好旅游标准、申请和合规情况。' },
  'Kelola sertifikasi Muslim Friendly Tourism Anda dengan aman.': { en: 'Manage your Muslim Friendly Tourism certification securely.', zh: '安全管理您的穆斯林友好旅游认证。' },
  'Trusted certification onboarding': { en: 'Trusted certification onboarding', zh: '可信赖的认证入门流程' },
  'Elevating global standards for Muslim-friendly tourism.': { en: 'Elevating global standards for Muslim-friendly tourism.', zh: '提升穆斯林友好旅游的全球标准。' },
  'Join tourism providers completing the Muslim Friendly Tourism Certification process with a guided, secure, and transparent digital workflow.': { en: 'Join tourism providers completing the Muslim Friendly Tourism Certification process with a guided, secure, and transparent digital workflow.', zh: '加入旅游服务商，通过有指导、安全且透明的数字流程完成穆斯林友好旅游认证。' },
  'Lengkapi data di bawah ini untuk memulai proses sertifikasi Anda sebagai Pelaku Usaha (PU).': { en: 'Complete the data below to start your certification process as a business actor (PU).', zh: '填写以下资料，以企业用户（PU）身份开始您的认证流程。' },
  'Masukkan nomor sertifikat MFTC untuk memeriksa keaslian dan masa berlaku sertifikat.': { en: 'Enter the MFTC certificate number to check authenticity and validity.', zh: '输入 MFTC 证书编号以检查真实性和有效期。' },
  'Pantau seluruh pengajuan sertifikasi Muslim Friendly Tourism Anda.': { en: 'Monitor all your Muslim Friendly Tourism certification applications.', zh: '监控您的所有穆斯林友好旅游认证申请。' },
  'Lengkapi biodata usaha, legalitas NIB, alamat, dan kontak penanggung jawab untuk memulai pengajuan sertifikasi.': { en: 'Complete your business profile, NIB legality, address, and responsible contact to start certification.', zh: '完善企业资料、NIB 合法性、地址和负责人联系方式以开始认证。' },
  'Daftar sertifikat aktif untuk seluruh lokasi usaha Anda.': { en: 'List of active certificates for all your business locations.', zh: '您所有营业地点的有效证书列表。' },
  'Sertifikat akan muncul di sini setelah pengajuan Anda disetujui dan diterbitkan oleh tim MFTC.': { en: 'Certificates will appear here after your application is approved and issued by the MFTC team.', zh: '您的申请获批并由 MFTC 团队签发后，证书将显示在此处。' },
  'Pengajuan': { en: 'Applications', zh: '申请' },
  'Sertifikat': { en: 'Certificates', zh: '证书' },
  'Pelaku Usaha': { en: 'Business Actor', zh: '企业用户' },
  'Pusat Bantuan': { en: 'Help Center', zh: '帮助中心' },
  'One Star': { en: 'One Star', zh: '一星' },
  'Two Star': { en: 'Two Star', zh: '二星' },
  'Three Star': { en: 'Three Star', zh: '三星' },
  DRAFT: { en: 'DRAFT', zh: '草稿' },
  SUBMITTED: { en: 'SUBMITTED', zh: '已提交' },
  INVOICED: { en: 'INVOICED', zh: '已开票' },
  PAID: { en: 'PAID', zh: '已付款' },
  REVISION: { en: 'REVISION', zh: '需修订' },
  APPROVED: { en: 'APPROVED', zh: '已批准' },
  CERTIFIED: { en: 'CERTIFIED', zh: '已认证' },
  CANCELLED: { en: 'CANCELLED', zh: '已取消' },
  EXPIRED: { en: 'EXPIRED', zh: '已过期' },
  'PAYMENT UPLOADED': { en: 'PAYMENT UPLOADED', zh: '付款凭证已上传' },
  'PAYMENT VERIFIED': { en: 'PAYMENT VERIFIED', zh: '付款已验证' },
  'READY FOR REVIEW': { en: 'READY FOR REVIEW', zh: '准备审核' },
  'AUDITOR ASSIGNED': { en: 'AUDITOR ASSIGNED', zh: '已分配审核员' },
  'SCHEDULE CONFIRMED': { en: 'SCHEDULE CONFIRMED', zh: '日程已确认' },
  'AUDIT IN PROGRESS': { en: 'AUDIT IN PROGRESS', zh: '审核进行中' },
  'REPORT SUBMITTED': { en: 'REPORT SUBMITTED', zh: '报告已提交' },
  'AUTO CANCELLED': { en: 'AUTO CANCELLED', zh: '自动取消' },
}

const locales: Record<Language, string> = {
  id: 'id-ID',
  en: 'en-US',
  zh: 'zh-CN',
}

interface LanguageContextValue {
  language: Language
  locale: string
  setLanguage: (language: Language) => void
  t: (key: string, params?: Params) => string
}

const LanguageContext = createContext<LanguageContextValue | null>(null)

function initialLanguage(): Language {
  if (typeof window === 'undefined') {
    return 'id'
  }

  const stored = window.localStorage.getItem(LANGUAGE_KEY)
  return stored === 'en' || stored === 'zh' || stored === 'id' ? stored : 'id'
}

function translateText(text: string, language: Language): string {
  if (language === 'id') {
    return text
  }

  const trimmed = text.trim()
  if (!trimmed) {
    return text
  }

  let translatedText = text
  const entries = Object.entries(phraseTranslations).sort((a, b) => b[0].length - a[0].length)

  for (const [source, translations] of entries) {
    const translated = translations[language]
    if (translated && translatedText.includes(source)) {
      translatedText = translatedText.split(source).join(translated)
    }
  }

  return translatedText
}

function translateDom(language: Language): void {
  if (typeof document === 'undefined') {
    return
  }

  const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT, {
    acceptNode(node) {
      const parent = node.parentElement
      if (!parent || ['SCRIPT', 'STYLE', 'OPTION'].includes(parent.tagName)) {
        return NodeFilter.FILTER_REJECT
      }

      return node.textContent?.trim() ? NodeFilter.FILTER_ACCEPT : NodeFilter.FILTER_REJECT
    },
  })

  const nodes: Text[] = []
  while (walker.nextNode()) {
    nodes.push(walker.currentNode as Text)
  }

  for (const node of nodes) {
    const original = node.parentElement?.dataset.i18nOriginalText ?? node.textContent ?? ''
    if (node.parentElement && !node.parentElement.dataset.i18nOriginalText) {
      node.parentElement.dataset.i18nOriginalText = original
    }
    node.textContent = translateText(original, language)
  }

  for (const element of document.querySelectorAll<HTMLInputElement | HTMLTextAreaElement>('[placeholder]')) {
    const original = element.dataset.i18nOriginalPlaceholder ?? element.placeholder
    if (!element.dataset.i18nOriginalPlaceholder) {
      element.dataset.i18nOriginalPlaceholder = original
    }
    element.placeholder = translateText(original, language)
  }
}

function interpolate(text: string, params?: Params): string {
  if (!params) {
    return text
  }

  return Object.entries(params).reduce(
    (value, [key, replacement]) => value.replaceAll(`{${key}}`, String(replacement)),
    text,
  )
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(initialLanguage)

  const setLanguage = (nextLanguage: Language) => {
    setLanguageState(nextLanguage)
    window.localStorage.setItem(LANGUAGE_KEY, nextLanguage)
  }

  useEffect(() => {
    const translate = () => translateDom(language)
    translate()

    const observer = new MutationObserver(() => translate())
    observer.observe(document.body, { childList: true, subtree: true })

    return () => observer.disconnect()
  }, [language])

  const value = useMemo<LanguageContextValue>(
    () => ({
      language,
      locale: locales[language],
      setLanguage,
      t: (key: string, params?: Params) => {
        const text = messages[language][key] ?? messages.id[key] ?? key
        return interpolate(text, params)
      },
    }),
    [language],
  )

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export function useLanguage(): LanguageContextValue {
  const ctx = useContext(LanguageContext)
  if (!ctx) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }

  return ctx
}
